---
- name: Install
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - ntp

- name: Uninstall
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - chrony

- name: enable and start ntpd
  service:
    name: ntpd
    state: started
    enabled: yes
